site_name: Katon Verification Language
site_url: https://katon-lang.github.io
repo_url: https://github.com/katon-lang/katon
repo_name: katon-lang/katon
theme: 
  name: material
  palette:
    scheme: default
    primary: indigo
  font:
    code: Roboto
  icon:
    logo: fontawesome/solid/fire
nav:
  - Home: index.md
  - Semantics: semantics.md
copyright: Copyright &copy; 2025 Katon Project